language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update
  - sudo apt-get install --yes devscripts equivs
  - sudo mk-build-deps -i -r -t " apt-get --no-install-recommends --yes"

script:
  - ./autogen.sh
  - ./configure --prefix=$HOME
  - make
  - make check
  - make install

after_success:

env:
  global:
    - OBS_HOME=security
    - OBS_PROJECT=Zorp
    - OBS_MAJOR_VERSION=6
    - OBS_MINOR_VERSION=0
    - OBS_MAINTENANCE_VERSION=8
    - OBS_PACKAGE=zorp
